### ISSUE TITLE
numwords error on web (3.3.4)

### ISSUE THREAD

**Issue by simplecohesion** [gameticharles/advance_math#1]
When using the 3.3.4 version of the library, compiling for web:

advance_math-3.3.4/lib/src/num_words/num_words.dart:350:32: Error: The integer literal 8666529123484656789 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in JavaScript. In JavaScript 8666529123484656640 is the nearest value that can be represented exactly.  displayConversion(converter, 8666529123484656789, lang: 'fr');

**Comment by gameticharles** [comment]
Thanks, this issue was fixed with a later version release.
