### ISSUE TITLE
correlation fails with type cast

### ISSUE THREAD

**Issue by isoos** [gameticharles/advance_math#2]
Unhandled exception:
type '(num, num) => num' is not a subtype of type '(double, double) => double' of 'combine'
#0      ListBase.reduce (dart:collection/list.dart:185:14)
#1      mean (package:advance_math/src/math/basic/statistics.dart:10:15)
#2      correlation (package:advance_math/src/math/basic/statistics.dart:214:18)

**Comment by gameticharles** [comment]
Thanks for the heads up, changed it to num type. It should work for all. 

Try version 3.3.8 and let me know if the error persists.
